# Generated by Django 5.2.12 on 2026-03-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('guardian_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('joining_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
