# Generated by Django 5.2.12 on 2026-03-29 17:16

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='contract',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='coaches/contracts/'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='license',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='coaches/licenses/'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='coaches/resumes/'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='contract',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='players/contracts/'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='medical_report',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='players/medical/'),
        ),
    ]
